version: '3.8'

services:
  # API Service
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
      target: runner
    container_name: tablehop-api-prod
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: ${DATABASE_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - "4000:4000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Web Service
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      target: runner
    container_name: tablehop-web-prod
    environment:
      VITE_API_URL: ${API_URL}
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped
